### ISSUE TITLE
Skydoc failed: error executing Skydoc command with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_sass#153]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3542#018c8f87-ac28-432a-80ce-2b59d1b21d01

Platform :  MAC

Logs:
```
RROR: /Users/buildkite/builds/bk-imacpro-5/bazel-org-repo-root/rules_sass/sass/docs/BUILD:5:12: Generating Skylark doc for docs (3 files) failed: (Exit 1): skydoc failed: error executing Skydoc command (from target //sass/docs:docs)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_buildkite/def0945ba6f6ced8e7aeaed9b3cc8588/sandbox/darwin-sandbox/231/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/_main/../io_bazel_skydoc/skydoc/main.py", line 19, in <module>
    import jinja2
  File "/private/var/tmp/_bazel_buildkite/def0945ba6f6ced8e7aeaed9b3cc8588/sandbox/darwin-sandbox/231/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/jinja2_archive/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/private/var/tmp/_bazel_buildkite/def0945ba6f6ced8e7aeaed9b3cc8588/sandbox/darwin-sandbox/231/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/jinja2_archive/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/private/var/tmp/_bazel_buildkite/def0945ba6f6ced8e7aeaed9b3cc8588/sandbox/darwin-sandbox/231/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/jinja2_archive/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/private/var/tmp/_bazel_buildkite/def0945ba6f6ced8e7aeaed9b3cc8588/sandbox/darwin-sandbox/231/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/jinja2_archive/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "/private/var/tmp/_bazel_buildkite/def0945ba6f6ced8e7aeaed9b3cc8588/sandbox/darwin-sandbox/231/execroot/_main/bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/markupsafe_archive/markupsafe/__init__.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' 

```

Steps:
```
git clone -v https://github.com/bazelbuild/rules_sass.git
git reset a9a447e887d7b558716d520ae88bc0426a29cbfc --hard
export USE_BAZEL_VERSION=20a8a206c49e2979ddc154296bc1715f5781bb0c
bazel build  //...
```

CC Greenteam @Wyverald

**Comment by sgowroji** [comment]
CC @[jelbourn](https://github.com/jelbourn)

**Comment by meteorcloudy** [comment]
`io_bazel_skydoc` should probably be updated @jelbourn

**Comment by meteorcloudy** [comment]
If this is not getting fixed, we should disable rules_sass in Bazel's downstream pipeline.

**Comment by jelbourn** [comment]
I'll see if I can find time to investigate this week, but disabling the CI for now seems reasonable. We do still use the rules for Angular, but we're behind on Bazel versions for other reasons
